### ISSUE TITLE
Problem running adcc: Prohibited to create memoryview without Py_buffer

### ISSUE THREAD

**Issue by BranisalavStankovic** [adc-connect/adcc#94] opened 2020-11-10 15:41 UTC
Hi all,

I tried to do 1st exampe (i. e. one named Getting a first taste) and it told me that it is "Prohibited to create memoryview without Py_buffer"

Below is the whole message.

So, what I have to do?

Best,
Branislav

/home/bane/PycharmProjects/ADC/venv/bin/python /home/bane/PycharmProjects/ADC/prime.py
converged SCF energy = -76.0571904154806
Traceback (most recent call last):
  File "/home/bane/PycharmProjects/ADC/prime.py", line 17, in <module>
    state = adcc.adc3(scfres, n_singlets=3)
  File "/home/bane/PycharmProjects/ADC/venv/lib/python3.6/site-packages/adcc/__init__.py", line 108, in adc3
    return run_adc(*args, **kwargs, method="adc3")
  File "/home/bane/PycharmProjects/ADC/venv/lib/python3.6/site-packages/adcc/workflow.py", line 175, in run_adc
    frozen_virtual=frozen_virtual, method=method)
  File "/home/bane/PycharmProjects/ADC/venv/lib/python3.6/site-packages/adcc/workflow.py", line 232, in construct_adcmatrix
    frozen_virtual=frozen_virtual)
  File "/home/bane/PycharmProjects/ADC/venv/lib/python3.6/site-packages/adcc/ReferenceState.py", line 146, in __init__
    core_orbitals=core_orbitals)
  File "/home/bane/PycharmProjects/ADC/venv/lib/python3.6/site-packages/adcc/MoSpaces.py", line 133, in __init__
    spaceargs["frozen_core"], spaceargs["frozen_virtual"])
RuntimeError: Prohibited to create memoryview without Py_buffer

Process finished with exit code 1

**Comment by maxscheurer** [comment] 2020-11-10 16:00
Hi,

sorry that you're having troubles with the example.
This is a problem caused by pybind11 version 2.6, which was used, in your case, to build the Python bindings for adcc.

Support for pybind11 2.6 is now also available in the current master branch, because we recently discovered this problem (see #93).
So, you need to re-build the adcc extensions after updating your checked out adcc version (`git pull --ff`).

Let us know if this does the job...

**Comment by BranisalavStankovic** [comment] 2020-11-11 21:44
Hi,

I am new to this so can you tell me in more details what I should do?

Best regards,
Branislav

**Comment by maxscheurer** [comment] 2020-11-11 21:47
Ok. How did you install `adcc` on your machine? (Possible options are via `conda`, `pip`, or from source...)

**Comment by BranisalavStankovic** [comment] 2020-11-11 22:05
pip or conda, not sure. One was working, other not. Think conda

**Comment by mfherbst** [comment] 2020-11-12 08:28
Since conda is distributed as binaries I would assume conda to work (If not please tell us, since that would not be on our radar).

The pip installation will likely fail at the moment, since by default pip will use  pybind11 2.6 that is incompatible with the lastest adcc. If you want to use pip, the simplest workaround at the moment is:
```shell
pip install "pybind11<2.6" "h5py<3.0" "adcc==0.15.1"
```
i.e. to pin the version of adcc and some of its dependencies to a known-to-work setup. I just tested this in a fresh virtualenv and it worked for me. Please let us know if not.

Current plan is to release a new version of adcc within the next week, which will have the issue fixed in either case.

**Comment by mfherbst** [comment] 2020-11-13 16:16
Closing as adcc 0.15.2 (containing the bugfix) has been released on PyPI.

**Closed by mfherbst** 2020-11-13 16:16 UTC
Labels: bug
